name: aichatapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6  # For API requests
  provider: ^6.0.5  # For state management
  cupertino_icons: ^1.0.8  # For iOS style icons
  google_generative_ai: ^0.0.1-dev
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
  open_file: ^3.3.2    # Opens files like PDFs
  flutter_spinkit: ^5.2.0
  speech_to_text: ^6.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/chatapp_wallpaper1.jpg
    - assets/chatapp_wallpaper2.jpg
    - assets/chatapp_wallpaper3.jpg
    - assets/chatapp_wallpaper4.jpg
    - assets/chatapp_wallpaper5.jpg
    - assets/chatapp_wallpaper6.jpg
    - assets/chatapp_wallpaper7.jpg
    - assets/chatapp_wallpaper8.jpg
    - assets/chatapp_wallpaper9.jpg
    - assets/chatapp_wallpaper10.jpg
